//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenshakovaBytService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseholdTech
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HouseholdTech()
        {
            this.Request = new HashSet<Request>();
        }
    
        public long Id { get; set; }
        public long TypeId { get; set; }
        public string Model { get; set; }
        public string Description { get; set; }
    
        public virtual HouseholdTechType HouseholdTechType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
